### ISSUE TITLE
Failed to load payment view

### ISSUE THREAD

**Issue by MubaHdev** [james-awo/remitta_flutter_inline_sdk#1]
Everything works until it gets to the point of displaying the webview, after loading for a while , it automatically calls the onclose method in the html and throwing this error in the console
{code: 00, message: SUCCESS, data: {paymentReference: , processorId: null, transactionId: , message: , amount: null}}

![Simulator Screen Shot - iPhone 14 Pro - 2022-10-05 at 10 41 21](https://user-images.githubusercontent.com/98467065/194031527-0d3fe1d3-0ff6-463c-bd3f-436b68953ec1.png)

**Comment by james-awo** [comment]
hi @MubaHdev can you provide steps to reproduce

**Comment by MubaHdev** [comment]
`  initializePayment(
      {required BuildContext context,
      required String rrr,
      required String key}) async {
    PaymentRequest request = PaymentRequest(
      environment: RemittaEnvironment.production,
      rrr: rrr,
      key: key,
    );
    print("1");

    RemittaPayment remitta = RemittaInlinePayment(
      buildContext: context,
      paymentRequest: request,
      customizer: Customizer(),
    );

    PaymentResponse response = await remitta.initiatePayment();


    if (response.code != null && response.code == '00') {
     log("Success");
    } else {
      log("Failed");

      // transaction not successful.
    }
    log(response.toString());
  }`


Thank you @james-awo, here is the code.

**Comment by james-awo** [comment]
@MubaHdev you have not provided information to reproduce your error. 
if you are using an older version try upgrading to `remitta_flutter_inline: ^1.0.1`.

**Comment by MubaHdev** [comment]
I'm using the latest version remitta_flutter_inline: ^1.0.1 and i pasted the code above.
I'm making a request to generate RRR code for every transaction the passing it to the package implementation
